services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_db:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8050:8050
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=han
      - ME_CONFIG_MONGODB_ADMINPASSWORD=han
      - ME_CONFIG_MONGODB_SERVER=mongodb

  volumes:
    mongo_db:

